# Site settings
title: Matt's Posts
email: matthew.tejo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My site to share some things Ive learned.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tejo.github.io" # the base hostname & protocol for your site
twitter_username: MatthewTejo
github_username:  tejom

# Build settings
markdown: kramdown
highlighter: rouge
